version: '3'
services:
      osm:
       build:
         context: .
         dockerfile: ./Dockerfile
       image: "openstreetmap:latest"
       ports:
         - 80:80
         - 5432:5432
       environment:
         - HOST= 0.0.0.0